/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserAgreementRouteImport } from './routes/user-agreement'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SystemSettingsRouteRouteImport } from './routes/system-settings/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SystemSettingsIndexRouteImport } from './routes/system-settings/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as RankingsIndexRouteImport } from './routes/rankings/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as KeysIndexRouteImport } from './routes/keys/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ChannelsIndexRouteImport } from './routes/channels/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as WalletRechargeRouteImport } from './routes/wallet/recharge'
import { Route as WalletOrdersRouteImport } from './routes/wallet/orders'
import { Route as OauthProviderRouteImport } from './routes/oauth/$provider'
import { Route as DashboardSectionRouteImport } from './routes/dashboard/$section'
import { Route as ConsoleTopupRouteImport } from './routes/console/topup'
import { Route as ConsoleLogRouteImport } from './routes/console/log'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetRouteImport } from './routes/(auth)/reset'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authOauthRouteImport } from './routes/(auth)/oauth'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as SystemSettingsSiteIndexRouteImport } from './routes/system-settings/site/index'
import { Route as SystemSettingsSecurityIndexRouteImport } from './routes/system-settings/security/index'
import { Route as SystemSettingsOperationsIndexRouteImport } from './routes/system-settings/operations/index'
import { Route as SystemSettingsModelsIndexRouteImport } from './routes/system-settings/models/index'
import { Route as SystemSettingsContentIndexRouteImport } from './routes/system-settings/content/index'
import { Route as SystemSettingsBillingIndexRouteImport } from './routes/system-settings/billing/index'
import { Route as SystemSettingsAuthIndexRouteImport } from './routes/system-settings/auth/index'
import { Route as PricingModelIdIndexRouteImport } from './routes/pricing/$modelId/index'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet/index'
import { Route as AuthenticatedUsageLogsIndexRouteImport } from './routes/_authenticated/usage-logs/index'
import { Route as AuthenticatedRedemptionCodesIndexRouteImport } from './routes/_authenticated/redemption-codes/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models/index'
import { Route as SystemSettingsSiteSectionRouteImport } from './routes/system-settings/site/$section'
import { Route as SystemSettingsSecuritySectionRouteImport } from './routes/system-settings/security/$section'
import { Route as SystemSettingsOperationsSectionRouteImport } from './routes/system-settings/operations/$section'
import { Route as SystemSettingsModelsSectionRouteImport } from './routes/system-settings/models/$section'
import { Route as SystemSettingsContentSectionRouteImport } from './routes/system-settings/content/$section'
import { Route as SystemSettingsBillingSectionRouteImport } from './routes/system-settings/billing/$section'
import { Route as SystemSettingsAuthSectionRouteImport } from './routes/system-settings/auth/$section'
import { Route as AuthenticatedUsageLogsSectionRouteImport } from './routes/_authenticated/usage-logs/$section'
import { Route as AuthenticatedModelsSectionRouteImport } from './routes/_authenticated/models/$section'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as authUserResetRouteImport } from './routes/(auth)/user/reset'

const UserAgreementRoute = UserAgreementRouteImport.update({
  id: '/user-agreement',
  path: '/user-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRouteRoute = SystemSettingsRouteRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsIndexRoute = SystemSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemSettingsRouteRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysIndexRoute = KeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRechargeRoute = WalletRechargeRouteImport.update({
  id: '/wallet/recharge',
  path: '/wallet/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletOrdersRoute = WalletOrdersRouteImport.update({
  id: '/wallet/orders',
  path: '/wallet/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthProviderRoute = OauthProviderRouteImport.update({
  id: '/oauth/$provider',
  path: '/oauth/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/dashboard/$section',
  path: '/dashboard/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleTopupRoute = ConsoleTopupRouteImport.update({
  id: '/console/topup',
  path: '/console/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleLogRoute = ConsoleLogRouteImport.update({
  id: '/console/log',
  path: '/console/log',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetRoute = authResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authOauthRoute = authOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const SystemSettingsSiteIndexRoute = SystemSettingsSiteIndexRouteImport.update({
  id: '/site/',
  path: '/site/',
  getParentRoute: () => SystemSettingsRouteRoute,
} as any)
const SystemSettingsSecurityIndexRoute =
  SystemSettingsSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsOperationsIndexRoute =
  SystemSettingsOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsModelsIndexRoute =
  SystemSettingsModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsContentIndexRoute =
  SystemSettingsContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsBillingIndexRoute =
  SystemSettingsBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsAuthIndexRoute = SystemSettingsAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => SystemSettingsRouteRoute,
} as any)
const PricingModelIdIndexRoute = PricingModelIdIndexRouteImport.update({
  id: '/pricing/$modelId/',
  path: '/pricing/$modelId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsageLogsIndexRoute =
  AuthenticatedUsageLogsIndexRouteImport.update({
    id: '/usage-logs/',
    path: '/usage-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedemptionCodesIndexRoute =
  AuthenticatedRedemptionCodesIndexRouteImport.update({
    id: '/redemption-codes/',
    path: '/redemption-codes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SystemSettingsSiteSectionRoute =
  SystemSettingsSiteSectionRouteImport.update({
    id: '/site/$section',
    path: '/site/$section',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsSecuritySectionRoute =
  SystemSettingsSecuritySectionRouteImport.update({
    id: '/security/$section',
    path: '/security/$section',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsOperationsSectionRoute =
  SystemSettingsOperationsSectionRouteImport.update({
    id: '/operations/$section',
    path: '/operations/$section',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsModelsSectionRoute =
  SystemSettingsModelsSectionRouteImport.update({
    id: '/models/$section',
    path: '/models/$section',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsContentSectionRoute =
  SystemSettingsContentSectionRouteImport.update({
    id: '/content/$section',
    path: '/content/$section',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsBillingSectionRoute =
  SystemSettingsBillingSectionRouteImport.update({
    id: '/billing/$section',
    path: '/billing/$section',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const SystemSettingsAuthSectionRoute =
  SystemSettingsAuthSectionRouteImport.update({
    id: '/auth/$section',
    path: '/auth/$section',
    getParentRoute: () => SystemSettingsRouteRoute,
  } as any)
const AuthenticatedUsageLogsSectionRoute =
  AuthenticatedUsageLogsSectionRouteImport.update({
    id: '/usage-logs/$section',
    path: '/usage-logs/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsSectionRoute =
  AuthenticatedModelsSectionRouteImport.update({
    id: '/models/$section',
    path: '/models/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authUserResetRoute = authUserResetRouteImport.update({
  id: '/user/reset',
  path: '/user/reset',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/system-settings': typeof SystemSettingsRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/user-agreement': typeof UserAgreementRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/oauth': typeof authOauthRoute
  '/otp': typeof authOtpRoute
  '/register': typeof authRegisterRoute
  '/reset': typeof authResetRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/console/log': typeof ConsoleLogRoute
  '/console/topup': typeof ConsoleTopupRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/oauth/$provider': typeof OauthProviderRoute
  '/wallet/orders': typeof WalletOrdersRoute
  '/wallet/recharge': typeof WalletRechargeRoute
  '/about/': typeof AboutIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/keys/': typeof KeysIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/system-settings/': typeof SystemSettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/user/reset': typeof authUserResetRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/models/$section': typeof AuthenticatedModelsSectionRoute
  '/usage-logs/$section': typeof AuthenticatedUsageLogsSectionRoute
  '/system-settings/auth/$section': typeof SystemSettingsAuthSectionRoute
  '/system-settings/billing/$section': typeof SystemSettingsBillingSectionRoute
  '/system-settings/content/$section': typeof SystemSettingsContentSectionRoute
  '/system-settings/models/$section': typeof SystemSettingsModelsSectionRoute
  '/system-settings/operations/$section': typeof SystemSettingsOperationsSectionRoute
  '/system-settings/security/$section': typeof SystemSettingsSecuritySectionRoute
  '/system-settings/site/$section': typeof SystemSettingsSiteSectionRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/redemption-codes/': typeof AuthenticatedRedemptionCodesIndexRoute
  '/usage-logs/': typeof AuthenticatedUsageLogsIndexRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
  '/pricing/$modelId/': typeof PricingModelIdIndexRoute
  '/system-settings/auth/': typeof SystemSettingsAuthIndexRoute
  '/system-settings/billing/': typeof SystemSettingsBillingIndexRoute
  '/system-settings/content/': typeof SystemSettingsContentIndexRoute
  '/system-settings/models/': typeof SystemSettingsModelsIndexRoute
  '/system-settings/operations/': typeof SystemSettingsOperationsIndexRoute
  '/system-settings/security/': typeof SystemSettingsSecurityIndexRoute
  '/system-settings/site/': typeof SystemSettingsSiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/user-agreement': typeof UserAgreementRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/oauth': typeof authOauthRoute
  '/otp': typeof authOtpRoute
  '/register': typeof authRegisterRoute
  '/reset': typeof authResetRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/console/log': typeof ConsoleLogRoute
  '/console/topup': typeof ConsoleTopupRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/oauth/$provider': typeof OauthProviderRoute
  '/wallet/orders': typeof WalletOrdersRoute
  '/wallet/recharge': typeof WalletRechargeRoute
  '/about': typeof AboutIndexRoute
  '/channels': typeof ChannelsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/keys': typeof KeysIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/rankings': typeof RankingsIndexRoute
  '/setup': typeof SetupIndexRoute
  '/system-settings': typeof SystemSettingsIndexRoute
  '/users': typeof UsersIndexRoute
  '/user/reset': typeof authUserResetRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/models/$section': typeof AuthenticatedModelsSectionRoute
  '/usage-logs/$section': typeof AuthenticatedUsageLogsSectionRoute
  '/system-settings/auth/$section': typeof SystemSettingsAuthSectionRoute
  '/system-settings/billing/$section': typeof SystemSettingsBillingSectionRoute
  '/system-settings/content/$section': typeof SystemSettingsContentSectionRoute
  '/system-settings/models/$section': typeof SystemSettingsModelsSectionRoute
  '/system-settings/operations/$section': typeof SystemSettingsOperationsSectionRoute
  '/system-settings/security/$section': typeof SystemSettingsSecuritySectionRoute
  '/system-settings/site/$section': typeof SystemSettingsSiteSectionRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/redemption-codes': typeof AuthenticatedRedemptionCodesIndexRoute
  '/usage-logs': typeof AuthenticatedUsageLogsIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
  '/pricing/$modelId': typeof PricingModelIdIndexRoute
  '/system-settings/auth': typeof SystemSettingsAuthIndexRoute
  '/system-settings/billing': typeof SystemSettingsBillingIndexRoute
  '/system-settings/content': typeof SystemSettingsContentIndexRoute
  '/system-settings/models': typeof SystemSettingsModelsIndexRoute
  '/system-settings/operations': typeof SystemSettingsOperationsIndexRoute
  '/system-settings/security': typeof SystemSettingsSecurityIndexRoute
  '/system-settings/site': typeof SystemSettingsSiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/system-settings': typeof SystemSettingsRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/user-agreement': typeof UserAgreementRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/oauth': typeof authOauthRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset': typeof authResetRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/console/log': typeof ConsoleLogRoute
  '/console/topup': typeof ConsoleTopupRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/oauth/$provider': typeof OauthProviderRoute
  '/wallet/orders': typeof WalletOrdersRoute
  '/wallet/recharge': typeof WalletRechargeRoute
  '/about/': typeof AboutIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/keys/': typeof KeysIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/system-settings/': typeof SystemSettingsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/(auth)/user/reset': typeof authUserResetRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/models/$section': typeof AuthenticatedModelsSectionRoute
  '/_authenticated/usage-logs/$section': typeof AuthenticatedUsageLogsSectionRoute
  '/system-settings/auth/$section': typeof SystemSettingsAuthSectionRoute
  '/system-settings/billing/$section': typeof SystemSettingsBillingSectionRoute
  '/system-settings/content/$section': typeof SystemSettingsContentSectionRoute
  '/system-settings/models/$section': typeof SystemSettingsModelsSectionRoute
  '/system-settings/operations/$section': typeof SystemSettingsOperationsSectionRoute
  '/system-settings/security/$section': typeof SystemSettingsSecuritySectionRoute
  '/system-settings/site/$section': typeof SystemSettingsSiteSectionRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/redemption-codes/': typeof AuthenticatedRedemptionCodesIndexRoute
  '/_authenticated/usage-logs/': typeof AuthenticatedUsageLogsIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
  '/pricing/$modelId/': typeof PricingModelIdIndexRoute
  '/system-settings/auth/': typeof SystemSettingsAuthIndexRoute
  '/system-settings/billing/': typeof SystemSettingsBillingIndexRoute
  '/system-settings/content/': typeof SystemSettingsContentIndexRoute
  '/system-settings/models/': typeof SystemSettingsModelsIndexRoute
  '/system-settings/operations/': typeof SystemSettingsOperationsIndexRoute
  '/system-settings/security/': typeof SystemSettingsSecurityIndexRoute
  '/system-settings/site/': typeof SystemSettingsSiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/system-settings'
    | '/privacy-policy'
    | '/user-agreement'
    | '/forgot-password'
    | '/oauth'
    | '/otp'
    | '/register'
    | '/reset'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/console/log'
    | '/console/topup'
    | '/dashboard/$section'
    | '/oauth/$provider'
    | '/wallet/orders'
    | '/wallet/recharge'
    | '/about/'
    | '/channels/'
    | '/dashboard/'
    | '/keys/'
    | '/pricing/'
    | '/rankings/'
    | '/setup/'
    | '/system-settings/'
    | '/users/'
    | '/user/reset'
    | '/errors/$error'
    | '/models/$section'
    | '/usage-logs/$section'
    | '/system-settings/auth/$section'
    | '/system-settings/billing/$section'
    | '/system-settings/content/$section'
    | '/system-settings/models/$section'
    | '/system-settings/operations/$section'
    | '/system-settings/security/$section'
    | '/system-settings/site/$section'
    | '/models/'
    | '/profile/'
    | '/redemption-codes/'
    | '/usage-logs/'
    | '/wallet/'
    | '/pricing/$modelId/'
    | '/system-settings/auth/'
    | '/system-settings/billing/'
    | '/system-settings/content/'
    | '/system-settings/models/'
    | '/system-settings/operations/'
    | '/system-settings/security/'
    | '/system-settings/site/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/user-agreement'
    | '/forgot-password'
    | '/oauth'
    | '/otp'
    | '/register'
    | '/reset'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/console/log'
    | '/console/topup'
    | '/dashboard/$section'
    | '/oauth/$provider'
    | '/wallet/orders'
    | '/wallet/recharge'
    | '/about'
    | '/channels'
    | '/dashboard'
    | '/keys'
    | '/pricing'
    | '/rankings'
    | '/setup'
    | '/system-settings'
    | '/users'
    | '/user/reset'
    | '/errors/$error'
    | '/models/$section'
    | '/usage-logs/$section'
    | '/system-settings/auth/$section'
    | '/system-settings/billing/$section'
    | '/system-settings/content/$section'
    | '/system-settings/models/$section'
    | '/system-settings/operations/$section'
    | '/system-settings/security/$section'
    | '/system-settings/site/$section'
    | '/models'
    | '/profile'
    | '/redemption-codes'
    | '/usage-logs'
    | '/wallet'
    | '/pricing/$modelId'
    | '/system-settings/auth'
    | '/system-settings/billing'
    | '/system-settings/content'
    | '/system-settings/models'
    | '/system-settings/operations'
    | '/system-settings/security'
    | '/system-settings/site'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_authenticated'
    | '/system-settings'
    | '/privacy-policy'
    | '/user-agreement'
    | '/(auth)/forgot-password'
    | '/(auth)/oauth'
    | '/(auth)/otp'
    | '/(auth)/register'
    | '/(auth)/reset'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/console/log'
    | '/console/topup'
    | '/dashboard/$section'
    | '/oauth/$provider'
    | '/wallet/orders'
    | '/wallet/recharge'
    | '/about/'
    | '/channels/'
    | '/dashboard/'
    | '/keys/'
    | '/pricing/'
    | '/rankings/'
    | '/setup/'
    | '/system-settings/'
    | '/users/'
    | '/(auth)/user/reset'
    | '/_authenticated/errors/$error'
    | '/_authenticated/models/$section'
    | '/_authenticated/usage-logs/$section'
    | '/system-settings/auth/$section'
    | '/system-settings/billing/$section'
    | '/system-settings/content/$section'
    | '/system-settings/models/$section'
    | '/system-settings/operations/$section'
    | '/system-settings/security/$section'
    | '/system-settings/site/$section'
    | '/_authenticated/models/'
    | '/_authenticated/profile/'
    | '/_authenticated/redemption-codes/'
    | '/_authenticated/usage-logs/'
    | '/_authenticated/wallet/'
    | '/pricing/$modelId/'
    | '/system-settings/auth/'
    | '/system-settings/billing/'
    | '/system-settings/content/'
    | '/system-settings/models/'
    | '/system-settings/operations/'
    | '/system-settings/security/'
    | '/system-settings/site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SystemSettingsRouteRoute: typeof SystemSettingsRouteRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  UserAgreementRoute: typeof UserAgreementRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  ConsoleLogRoute: typeof ConsoleLogRoute
  ConsoleTopupRoute: typeof ConsoleTopupRoute
  DashboardSectionRoute: typeof DashboardSectionRoute
  OauthProviderRoute: typeof OauthProviderRoute
  WalletOrdersRoute: typeof WalletOrdersRoute
  WalletRechargeRoute: typeof WalletRechargeRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  KeysIndexRoute: typeof KeysIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PricingModelIdIndexRoute: typeof PricingModelIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-agreement': {
      id: '/user-agreement'
      path: '/user-agreement'
      fullPath: '/user-agreement'
      preLoaderRoute: typeof UserAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-settings': {
      id: '/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof SystemSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-settings/': {
      id: '/system-settings/'
      path: '/'
      fullPath: '/system-settings/'
      preLoaderRoute: typeof SystemSettingsIndexRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys/': {
      id: '/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof KeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/': {
      id: '/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/recharge': {
      id: '/wallet/recharge'
      path: '/wallet/recharge'
      fullPath: '/wallet/recharge'
      preLoaderRoute: typeof WalletRechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/orders': {
      id: '/wallet/orders'
      path: '/wallet/orders'
      fullPath: '/wallet/orders'
      preLoaderRoute: typeof WalletOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/$provider': {
      id: '/oauth/$provider'
      path: '/oauth/$provider'
      fullPath: '/oauth/$provider'
      preLoaderRoute: typeof OauthProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$section': {
      id: '/dashboard/$section'
      path: '/dashboard/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/topup': {
      id: '/console/topup'
      path: '/console/topup'
      fullPath: '/console/topup'
      preLoaderRoute: typeof ConsoleTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/log': {
      id: '/console/log'
      path: '/console/log'
      fullPath: '/console/log'
      preLoaderRoute: typeof ConsoleLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset': {
      id: '/(auth)/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof authResetRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/oauth': {
      id: '/(auth)/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof authOauthRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/system-settings/site/': {
      id: '/system-settings/site/'
      path: '/site'
      fullPath: '/system-settings/site/'
      preLoaderRoute: typeof SystemSettingsSiteIndexRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/security/': {
      id: '/system-settings/security/'
      path: '/security'
      fullPath: '/system-settings/security/'
      preLoaderRoute: typeof SystemSettingsSecurityIndexRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/operations/': {
      id: '/system-settings/operations/'
      path: '/operations'
      fullPath: '/system-settings/operations/'
      preLoaderRoute: typeof SystemSettingsOperationsIndexRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/models/': {
      id: '/system-settings/models/'
      path: '/models'
      fullPath: '/system-settings/models/'
      preLoaderRoute: typeof SystemSettingsModelsIndexRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/content/': {
      id: '/system-settings/content/'
      path: '/content'
      fullPath: '/system-settings/content/'
      preLoaderRoute: typeof SystemSettingsContentIndexRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/billing/': {
      id: '/system-settings/billing/'
      path: '/billing'
      fullPath: '/system-settings/billing/'
      preLoaderRoute: typeof SystemSettingsBillingIndexRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/auth/': {
      id: '/system-settings/auth/'
      path: '/auth'
      fullPath: '/system-settings/auth/'
      preLoaderRoute: typeof SystemSettingsAuthIndexRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/pricing/$modelId/': {
      id: '/pricing/$modelId/'
      path: '/pricing/$modelId'
      fullPath: '/pricing/$modelId/'
      preLoaderRoute: typeof PricingModelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usage-logs/': {
      id: '/_authenticated/usage-logs/'
      path: '/usage-logs'
      fullPath: '/usage-logs/'
      preLoaderRoute: typeof AuthenticatedUsageLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redemption-codes/': {
      id: '/_authenticated/redemption-codes/'
      path: '/redemption-codes'
      fullPath: '/redemption-codes/'
      preLoaderRoute: typeof AuthenticatedRedemptionCodesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/system-settings/site/$section': {
      id: '/system-settings/site/$section'
      path: '/site/$section'
      fullPath: '/system-settings/site/$section'
      preLoaderRoute: typeof SystemSettingsSiteSectionRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/security/$section': {
      id: '/system-settings/security/$section'
      path: '/security/$section'
      fullPath: '/system-settings/security/$section'
      preLoaderRoute: typeof SystemSettingsSecuritySectionRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/operations/$section': {
      id: '/system-settings/operations/$section'
      path: '/operations/$section'
      fullPath: '/system-settings/operations/$section'
      preLoaderRoute: typeof SystemSettingsOperationsSectionRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/models/$section': {
      id: '/system-settings/models/$section'
      path: '/models/$section'
      fullPath: '/system-settings/models/$section'
      preLoaderRoute: typeof SystemSettingsModelsSectionRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/content/$section': {
      id: '/system-settings/content/$section'
      path: '/content/$section'
      fullPath: '/system-settings/content/$section'
      preLoaderRoute: typeof SystemSettingsContentSectionRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/billing/$section': {
      id: '/system-settings/billing/$section'
      path: '/billing/$section'
      fullPath: '/system-settings/billing/$section'
      preLoaderRoute: typeof SystemSettingsBillingSectionRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/system-settings/auth/$section': {
      id: '/system-settings/auth/$section'
      path: '/auth/$section'
      fullPath: '/system-settings/auth/$section'
      preLoaderRoute: typeof SystemSettingsAuthSectionRouteImport
      parentRoute: typeof SystemSettingsRouteRoute
    }
    '/_authenticated/usage-logs/$section': {
      id: '/_authenticated/usage-logs/$section'
      path: '/usage-logs/$section'
      fullPath: '/usage-logs/$section'
      preLoaderRoute: typeof AuthenticatedUsageLogsSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/$section': {
      id: '/_authenticated/models/$section'
      path: '/models/$section'
      fullPath: '/models/$section'
      preLoaderRoute: typeof AuthenticatedModelsSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/user/reset': {
      id: '/(auth)/user/reset'
      path: '/user/reset'
      fullPath: '/user/reset'
      preLoaderRoute: typeof authUserResetRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOauthRoute: typeof authOauthRoute
  authOtpRoute: typeof authOtpRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetRoute: typeof authResetRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authUserResetRoute: typeof authUserResetRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOauthRoute: authOauthRoute,
  authOtpRoute: authOtpRoute,
  authRegisterRoute: authRegisterRoute,
  authResetRoute: authResetRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authUserResetRoute: authUserResetRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedModelsSectionRoute: typeof AuthenticatedModelsSectionRoute
  AuthenticatedUsageLogsSectionRoute: typeof AuthenticatedUsageLogsSectionRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedRedemptionCodesIndexRoute: typeof AuthenticatedRedemptionCodesIndexRoute
  AuthenticatedUsageLogsIndexRoute: typeof AuthenticatedUsageLogsIndexRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedModelsSectionRoute: AuthenticatedModelsSectionRoute,
  AuthenticatedUsageLogsSectionRoute: AuthenticatedUsageLogsSectionRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedRedemptionCodesIndexRoute:
    AuthenticatedRedemptionCodesIndexRoute,
  AuthenticatedUsageLogsIndexRoute: AuthenticatedUsageLogsIndexRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SystemSettingsRouteRouteChildren {
  SystemSettingsIndexRoute: typeof SystemSettingsIndexRoute
  SystemSettingsAuthSectionRoute: typeof SystemSettingsAuthSectionRoute
  SystemSettingsBillingSectionRoute: typeof SystemSettingsBillingSectionRoute
  SystemSettingsContentSectionRoute: typeof SystemSettingsContentSectionRoute
  SystemSettingsModelsSectionRoute: typeof SystemSettingsModelsSectionRoute
  SystemSettingsOperationsSectionRoute: typeof SystemSettingsOperationsSectionRoute
  SystemSettingsSecuritySectionRoute: typeof SystemSettingsSecuritySectionRoute
  SystemSettingsSiteSectionRoute: typeof SystemSettingsSiteSectionRoute
  SystemSettingsAuthIndexRoute: typeof SystemSettingsAuthIndexRoute
  SystemSettingsBillingIndexRoute: typeof SystemSettingsBillingIndexRoute
  SystemSettingsContentIndexRoute: typeof SystemSettingsContentIndexRoute
  SystemSettingsModelsIndexRoute: typeof SystemSettingsModelsIndexRoute
  SystemSettingsOperationsIndexRoute: typeof SystemSettingsOperationsIndexRoute
  SystemSettingsSecurityIndexRoute: typeof SystemSettingsSecurityIndexRoute
  SystemSettingsSiteIndexRoute: typeof SystemSettingsSiteIndexRoute
}

const SystemSettingsRouteRouteChildren: SystemSettingsRouteRouteChildren = {
  SystemSettingsIndexRoute: SystemSettingsIndexRoute,
  SystemSettingsAuthSectionRoute: SystemSettingsAuthSectionRoute,
  SystemSettingsBillingSectionRoute: SystemSettingsBillingSectionRoute,
  SystemSettingsContentSectionRoute: SystemSettingsContentSectionRoute,
  SystemSettingsModelsSectionRoute: SystemSettingsModelsSectionRoute,
  SystemSettingsOperationsSectionRoute: SystemSettingsOperationsSectionRoute,
  SystemSettingsSecuritySectionRoute: SystemSettingsSecuritySectionRoute,
  SystemSettingsSiteSectionRoute: SystemSettingsSiteSectionRoute,
  SystemSettingsAuthIndexRoute: SystemSettingsAuthIndexRoute,
  SystemSettingsBillingIndexRoute: SystemSettingsBillingIndexRoute,
  SystemSettingsContentIndexRoute: SystemSettingsContentIndexRoute,
  SystemSettingsModelsIndexRoute: SystemSettingsModelsIndexRoute,
  SystemSettingsOperationsIndexRoute: SystemSettingsOperationsIndexRoute,
  SystemSettingsSecurityIndexRoute: SystemSettingsSecurityIndexRoute,
  SystemSettingsSiteIndexRoute: SystemSettingsSiteIndexRoute,
}

const SystemSettingsRouteRouteWithChildren =
  SystemSettingsRouteRoute._addFileChildren(SystemSettingsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SystemSettingsRouteRoute: SystemSettingsRouteRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  UserAgreementRoute: UserAgreementRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  ConsoleLogRoute: ConsoleLogRoute,
  ConsoleTopupRoute: ConsoleTopupRoute,
  DashboardSectionRoute: DashboardSectionRoute,
  OauthProviderRoute: OauthProviderRoute,
  WalletOrdersRoute: WalletOrdersRoute,
  WalletRechargeRoute: WalletRechargeRoute,
  AboutIndexRoute: AboutIndexRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  KeysIndexRoute: KeysIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  PricingModelIdIndexRoute: PricingModelIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
